### ISSUE TITLE
Missing InvalidCmdLine on Windows

### ISSUE THREAD

**Issue by rguiscard** [jiacai2050/simargs#2]
I ran simargs on Windows and it raised an error about missing InvalidCmdLine. I dig into this error in Zig and found it is windows specific. I can fixed it by adding it into ParseError like this:

`const ParseError = error{ NoProgram, NoOption, MissingRequiredOption, MissingOptionValue, InvalidEnumValue, InvalidCmdLine };`

Not sure it is the correct solution, though.

**Comment by jiacai2050** [comment]
Thanks for report, fixed in main.
