### ISSUE TITLE
"comptime inline for" seems not necessary

### ISSUE THREAD

**Issue by tt67wq** [jiacai2050/simargs#4]
In line 57 in simargs.zig
```
comptime inline for (std.meta.fields(shorts_type)) |fld| {
 // ...
};
```
can be just
```
inline for (std.meta.fields(shorts_type)) |fld| {....}
```

**Comment by jiacai2050** [comment]
I'm afraid not.

`inline for` means unroll the loop, but loop body still execute at runtime.

Loop body can run at compile time with comptime.

**Comment by jiacai2050** [comment]
https://www.reddit.com/r/Zig/comments/rvm6al/shouldnt_inline_be_just_comptime/

**Comment by tt67wq** [comment]
> I'm afraid not.
> 
> `inline for` means unroll the loop, but loop body still execute at runtime.
> 
> Loop body can run at compile time with comptime.

but in 'parse messages' part, u use `inline for` without `comptime`, why?
```
    // parse messages
    if (@hasDecl(T, "__messages__")) {
        const messages_type = @TypeOf(T.__messages__);
        if (@typeInfo(messages_type) != .Struct) {
            @compileError("__messages__ should be defined using struct, found " ++ @typeName(@typeInfo(messages_type)));
        }

        inline for (std.meta.fields(messages_type)) |fld| {
            const long_name = fld.name;
            inline for (opt_fields) |*opt_fld| {
               // ......
            } else {
                @compileError("no such option exists, long_name: " ++ long_name);
            }
        }
    }
```

**Comment by jiacai2050** [comment]
Ooops, I just check that `parseOptionField()` is called with `comptime`, so `comptime` is unnecessary inside it.

Welcome to open an PR to fix this.
